/// Reference:
/// https://github.com/fdeantoni/prost-wkt
/// https://github.com/hyperium/tonic/tree/master/tonic-build
/// https://github.com/tokio-rs/prost/issues/672
fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=proto/google/bigtable/v2/session.proto");

    #[cfg(feature = "sessions")]
    build_sessions();

    // Conditionally run the test-proto generator so we do not need protoc
    // for normal builds. Set BUILD_BIGTABLE_RS_GOOGLE_PROTO=true when
    // regenerating the test conformance protos.
    match std::env::var("BUILD_BIGTABLE_RS_GOOGLE_PROTO") {
        Ok(var) => {
            if var != "true" {
                return Ok(());
            }
        }
        Err(_) => return Ok(()),
    }

    println!(
        "cargo:warning=Running build.rs to generate and format Google API Bigtable proto rs files."
    );

    use prost_wkt_build::{FileDescriptorSet, Message};
    use std::{env, path::PathBuf};

    // Build test protos
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let descriptor_file = out.join("descriptors.bin");
    tonic_prost_build::configure()
        .build_server(false)
        .out_dir("tests/read_rows/google")
        .compile_well_known_types(true)
        .type_attribute(".", "#[serde_with::serde_as]")
        .type_attribute(".", "#[derive(serde::Serialize,serde::Deserialize)]")
        .type_attribute(".", "#[serde(rename_all = \"camelCase\")]")
        .type_attribute(
            ".google.cloud.conformance.bigtable.v2.ReadRowsTest",
            "#[serde(default)]",
        )
        .field_attribute(
            ".google.cloud.conformance.bigtable.v2.ReadRowsTest.Result.timestamp_micros",
            "#[serde_as(as = \"serde_with::DisplayFromStr\")]",
        )
        .extern_path(
            ".google.protobuf.BytesValue",
            "::prost::alloc::vec::Vec<u8>",
        )
        .extern_path(
            ".google.protobuf.StringValue",
            "::prost::alloc::string::String",
        )
        .extern_path(
            ".google.cloud.conformance.bigtable.v2.ReadRowsTest.CellChunkWithSerde",
            "crate::read_rows::types_with_serde::CellChunkWithSerde",
        )
        // todo type change
        .extern_path(".google.protobuf", "::prost_wkt_types")
        .file_descriptor_set_path(&descriptor_file)
        .compile_protos(&["./tests/bigtable_test.proto"], &["tests"])?;

    let descriptor_bytes = std::fs::read(descriptor_file).unwrap();
    let descriptor = FileDescriptorSet::decode(&descriptor_bytes[..]).unwrap();
    prost_wkt_build::add_serde(out, descriptor);

    std::process::Command::new("cargo")
        .arg("fmt")
        .output()
        .expect("Running `cargo fmt` failed");

    Ok(())
}

/// Generates Rust bindings for `google/bigtable/v2/session.proto` when the
/// `sessions` feature is enabled. Skipped otherwise so users who don't opt
/// into Sessions don't pay the protoc build cost.
///
/// session.proto imports data.proto, types.proto, request_stats.proto,
/// feature_flags.proto, peer_info.proto, and response_params.proto — all of
/// which are already generated by `googleapis-tonic-google-bigtable-v2`.
/// We redirect every type they define via `extern_path` so our generated
/// module contains *only* the session-family types.
#[cfg(feature = "sessions")]
fn build_sessions() {
    let proto_root = std::path::PathBuf::from("proto");
    let session_proto = proto_root.join("google/bigtable/v2/session.proto");

    // Types defined in imported .proto files that already exist in
    // `googleapis-tonic-google-bigtable-v2` — redirect to that crate rather
    // than regenerating.
    let bigtable_v2_types = [
        // data.proto
        "ArrayValue",
        "Cell",
        "Column",
        "ColumnMetadata",
        "ColumnRange",
        "Family",
        "Idempotency",
        "Mutation",
        "PartialResultSet",
        "ProtoFormat",
        "ProtoRows",
        "ProtoRowsBatch",
        "ProtoSchema",
        "ReadModifyWriteRule",
        "ResultSetMetadata",
        "Row",
        "RowFilter",
        "RowRange",
        "RowSet",
        "StreamContinuationToken",
        "StreamContinuationTokens",
        "StreamPartition",
        "TimestampRange",
        "Value",
        "ValueBitmask",
        "ValueRange",
        // types.proto
        "Type",
        // request_stats.proto
        "FullReadStatsView",
        "ReadIterationStats",
        "RequestLatencyStats",
        "RequestStats",
        // feature_flags.proto
        "FeatureFlags",
        // peer_info.proto
        "PeerInfo",
        // response_params.proto
        "ResponseParams",
    ];

    let mut config = tonic_prost_build::configure()
        .build_client(true)
        .build_server(false)
        .compile_well_known_types(false);

    for ty in bigtable_v2_types {
        config = config.extern_path(
            format!(".google.bigtable.v2.{ty}"),
            format!("::googleapis_tonic_google_bigtable_v2::google::bigtable::v2::{ty}"),
        );
    }

    // google.rpc.* — redirect to existing crate.
    config = config
        .extern_path(
            ".google.rpc.Status",
            "::googleapis_tonic_google_rpc::google::rpc::Status",
        )
        .extern_path(
            ".google.rpc.RetryInfo",
            "::googleapis_tonic_google_rpc::google::rpc::RetryInfo",
        );

    config
        .compile_protos(&[session_proto], &[proto_root])
        .expect("failed to compile session.proto");
}
