name: bigtable_rs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # macOS-latest is ignored for now as there is no docker on it, also we might not really need to verify on mac

    steps:
      - name: Start Bigtable Emulator
        run: |
          docker run --rm -d -p 8086:8086 --name bigtable-emulator \
          google/cloud-sdk:latest \
          gcloud beta emulators bigtable start --host-port=0.0.0.0:8086

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, llvm-tools-preview
          # This action automatically handles caching for ~/.cargo and ./target

      - name: Install Tools (Protoc & cargo-llvm-cov)
        uses: taiki-e/install-action@v2
        with:
          tool: protoc, cargo-llvm-cov

      - name: Check fmt
        run: cargo fmt -- --check
      
      - name: Cargo build
        run: cargo build
        env:
          BUILD_BIGTABLE_RS_GOOGLE_PROTO: 'true'
      
      - name: Check git status clean
        uses: CatChen/check-git-status-action@v1
        with:
          fail-if-not-clean: true

      - name: Generate Code Coverage
        # This  both 'Run tests'
        # --lcov: generates the file for Codecov
        # --ignore-filename-regex: excludes your google/ folder
        env:
          BIGTABLE_EMULATOR_HOST: localhost:8086

        # Use cargo llvm-cov to run test and generate coverage report
        # For local running, use command:
        # BIGTABLE_EMULATOR_HOST=localhost:8086 cargo llvm-cov --no-cfg-coverage  --ignore-filename-regex "google/" --features integration_tests --html --open
        run: >
          cargo llvm-cov --no-cfg-coverage --lcov --output-path lcov.info
          --ignore-filename-regex "google/" --features integration_tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./lcov.info
          flags: rust
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Emulator Logs on Failure
        if: failure() # Only runs if the tests (or setup) fail
        run: docker logs bigtable-emulator


  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    needs: test # <--- CRITICAL: release-plz-release won't start until 'test' passes
    if: |
      github.repository_owner == 'liufuyang' &&
      github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write
      pull-requests: read
      id-token: write # Required for Trusted Publishing
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz creating PR
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'liufuyang' &&
      github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
